Development - Pull Request 12Jun2020
charre2017idv/buzzshockEngine pull request #1
Opened 2020-06-13 00:36 UTC by charre2017idv

This pull request contains the next information:

- [ ] buMath.h 
- [x] buPlatformMath.h - This is for the basic math 
- [x] Plugger
- [x] Degrees
- [x] Radians
- [x] Vector2I - **Unit testing implemented**
- [x] Vector2f - **Unit testing implemented**
- [x] Vector3I - **Unit testing implemented**
- [x] Vector3f - **Unit testing implemented**
- [x] Vector4I - **Unit testing implemented**
- [x] Vector4f - **Unit testing implemented**
- [x] Matrix4x4 - **Unit testing implemented**
- [x] Quaternions - **Unit testing implemented** - _Need to check what other vector classes can be used_
- [ ] Shapes - Is the father of the next classes
  - [x] Rectangle - **Unit testing implemented**
  - [x] Box - **Unit testing implemented**
  - [x] Planes - **Unit testing implemented**
  - [x] Spheres - **Unit testing implemented** - _Need to check equation._ 
  - [X] Rays - **Unit testing implemented**
  - [ ] Frustrum

2020-06-15 05:32 UTC, NeonGE requested changes
Tírame toda la documentación en HTML
Revisa los comentarios, aplican para todo el código
Elimina los ZIP

2020-06-15 05:32 UTC, NeonGE commented on buUtilities/include/buBox.h
> +		float m_length;
Este tipo de estructura requiere posiciones, no solo tamaño

2020-06-15 05:32 UTC, NeonGE commented on buUtilities/include/buDegrees.h
> +		/**
Falta creacion con Radianes

2020-06-15 05:32 UTC, NeonGE commented on buUtilities/include/buDegrees.h
> +		getRadians();
Estandariza los getters en ambas clases

2020-06-15 05:32 UTC, NeonGE commented on buUtilities/include/buMath.h
> +
Faltan includes de sistema

2020-06-15 05:32 UTC, NeonGE commented on buUtilities/include/buMatrix4x4.h
> +		void
Esto debería de regresar la dirección de este objeto

2020-06-15 05:32 UTC, NeonGE commented on buUtilities/include/buMatrix4x4.h
> +		void
Esto debería de regresar la dirección de este objeto

2020-06-15 05:32 UTC, NeonGE commented on buUtilities/include/buMatrix4x4.h
> +		det();
Usa nombres de función descriptivos

2020-06-15 05:32 UTC, NeonGE commented on buUtilities/include/buPlugger.h
> +/**
Cambia a Pluggin

2020-06-15 05:32 UTC, NeonGE commented on buUtilities/include/buPlugger.h
> +		HINSTANCE hInstance = LoadLibraryExA(
La instancia debe ser miembro de la clase

2020-06-15 05:32 UTC, NeonGE commented on buUtilities/include/buMatrix4x4.h
> +		static const buMatrix4x4 Zero;
Constantes en mayusculas

2020-06-15 05:32 UTC, NeonGE commented on buUtilities/include/buRectangle.h
> +		/**
Requiere posicion

2020-06-17 22:04 UTC, charre2017idv commented on buUtilities/include/buMatrix4x4.h
> +		void
Ya se corrigio este metodo.

2020-06-17 22:04 UTC, charre2017idv commented on buUtilities/include/buMatrix4x4.h
> +		void
Ya se corrigio este metodo

2020-06-17 22:05 UTC, charre2017idv commented on buUtilities/include/buMatrix4x4.h
> +		det();
Ya se corrigio el nombre de este metodo.

2020-06-17 22:07 UTC, charre2017idv commented on buUtilities/include/buMatrix4x4.h
> +		static const buMatrix4x4 Zero;
Ya se cambio a mayusculas esta constante

2020-06-17 22:11 UTC, charre2017idv commented on buUtilities/include/buRectangle.h
> +		/**
Ya se agrego una posicion a esta clase.

2020-06-17 22:12 UTC, charre2017idv commented on buUtilities/include/buPlugger.h
> +		HINSTANCE hInstance = LoadLibraryExA(
Ya se creo un miembro de la instancia.

2020-06-17 22:13 UTC, charre2017idv commented on buUtilities/include/buPlugger.h
> +/**
Ya se cambio el nombre de la clase.

2020-06-17 22:14 UTC, charre2017idv commented on buUtilities/include/buBox.h
> +		float m_length;
Ya se agrego posicion.

2020-06-17 23:30 UTC, charre2017idv commented on buUtilities/include/buDegrees.h
> +		getRadians();
Listo!

2020-06-17 23:31 UTC, charre2017idv commented on buUtilities/include/buDegrees.h
> +		/**
Listo!

2020-07-25 15:53 UTC, merged